name: Build APK
on:
  push:
    branches: main
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

      # - name: Bump version
      #   shell: bash
      #   run: |
      #     bash ./bump_version.sh patchVersionDevCode
      # - name: commit-push_branch-test
      #   uses: dsayling/commit-branch-check-action@v0.1.5
      #   with:
      #     github-token: ${{ secrets.GIT_TOKEN }}
      #     commit-message: "Update from ${{github.event.pull_request.head.ref}}"
      #     dest-branch: build/main
      - name: Extract branch name
        run: echo "patch_version=$((${{ secrets.MY_SECRET_NAME }}+1))" >> $GITHUB_ENV

      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'MY_SECRET_NAME'
          value: ${{ env.patch_version }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        run: echo "${{ env.patch_version }}" >> world.txt


      - name: Upload Test Failures
        uses: actions/upload-artifact@v3
        with:
          name: world
          path: world.txt