name: Build APK
on:
  push:
    branches: main
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access_token: ${{ secrets.GIT_TOKEN }}
          branch: ${{ github.event.repository.default_branch }}
          enforce_admins: false

      - uses: actions/checkout@v3

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

      - name: Bump version
        shell: bash
        run: |
          bash ./bump_version.sh patchVersionDevCode
      - name: commit-push_branch-test
        uses: dsayling/commit-branch-check-action@v0.1
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          commit-message: "Update from ${{github.event.pull_request.head.ref}}"
          dest-branch: ${{github.event.pull_request.head.sha }}-new
          verify-checks: true
          delete-after-checks: true

      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access_token: ${{ secrets.GIT_TOKEN }}
          branch: ${{ github.event.repository.default_branch }}
          enforce_admins: true