# .github/workflows/logger.yaml
name: Event Loggger
on: push

jobs:
  log-github-event-goodies:
    name: "LOG Everything on GitHub Event"
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"

      - name: Comment PR
        uses: 8BitJonny/gh-get-current-pr@2.1.2
        id: PR
        
      - name: Test
        run: echo "Your PR number is ${{ steps.PR.outputs.number }} and its JSON is ${{ steps.PR.outputs.pr }}"
