name: Build APK
on:
  push:
    branches: main
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

      - name: Bump version
        shell: bash
        run: |
          bash ./bump_version.sh patchVersionDevCode
      - name: commit-push_branch-test
        uses: dsayling/commit-branch-check-action@v0.1.5
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          commit-message: "Update from ${{github.event.pull_request.head.ref}}"
          dest-branch: build/main